Vagrant.configure("2") do |config|

  config.vm.define "Acontrol" do |acontrol|
    acontrol.vm.box = "ubuntu/bionic64"
    acontrol.vm.network "private_network", ip: "192.168.33.10"
    acontrol.vm.hostname = "acontrol"
    acontrol.vm.synced_folder ".", "/vagrant", type: "nfs"
      acontrol.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--name", "acontrol"]
      vb.memory = "2048"
      vb.cpus = "1"
    end
       acontrol.vm.provision "shell", inline: <<-SHELL
        sudo sed -i 's/XKBLAYOUT="us"/XKBLAYOUT="ch"/g' /etc/default/locale 
        sudo apt-get install software-properties-common -y
        sudo apt-add-repository ppa:ansible/ansible -y
        sudo apt-get update -y
        sudo apt-get upgrade -y
        sudo apt-get install ansible -y
        echo '127.0.0.1 localhost acontrol\n192.168.33.11 lb01\n192.168.33.12 app01\n192.168.33.13 app02' > /etc/hosts
        cp -r /vagrant/Ansible /home/vagrant/
        #ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa <<< y
        #sudo cp /home/vagrant/.ssh/id_rsa.pub /vagrant
   SHELL
  end
  
  config.vm.define "LoadBalancer" do |lb01|
    lb01.vm.box = "ubuntu/bionic64"
    lb01.vm.network "private_network", ip: "192.168.33.11"
    lb01.vm.network "forwarded_port", guest_ip: "192.168.33.11", guest: 80, host_ip:"127.0.0.1", host: 6969
    lb01.vm.hostname = "lb01"
    lb01.vm.synced_folder ".", "/vagrant", type: "nfs"
    lb01.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--name", "lb01"]
      vb.memory = "1024"
      vb.cpus = "1"
    end
    lb01.vm.provision "shell", inline: <<-SHELL
    sudo sed -i 's/XKBLAYOUT="us"/XKBLAYOUT="ch"/g' /etc/default/locale
    sudo apt-get update -y
    sudo apt-get upgrade -y
    echo '127.0.0.1 localhost lb01\n192.168.33.10 acontrol\n192.168.33.12 app01\n192.168.33.13 app02' > /etc/hosts
    #cat /vagrant/id_rsa.pub >>/home/vagrant/.ssh/authorized_keys
SHELL
  end

  config.vm.define "WebServer1" do |app01|
    app01.vm.box = "ubuntu/bionic64"
    app01.vm.network "private_network", ip: "192.168.33.12"
    #app01.vm.network "forwarded_port", guest_ip: "10.0.2.17", guest: 8080, host_ip:"127.0.0.1", host: 8888
    app01.vm.hostname = "app01"
    app01.vm.synced_folder ".", "/vagrant", type: "nfs"
    app01.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--name", "app01"]
      vb.memory = "1024"
      vb.cpus = "1"
    end
    app01.vm.provision "shell", inline: <<-SHELL
    sudo sed -i 's/XKBLAYOUT="us"/XKBLAYOUT="ch"/g' /etc/default/locale
    sudo apt-get update -y
    sudo apt-get upgrade -y
    echo '127.0.0.1 localhost app01\n192.168.33.11 lb01\n192.168.33.10 acontrol\n192.168.33.13 app02' > /etc/hosts
    #cat /vagrant/id_rsa.pub >>~/.ssh/authorized_keys
SHELL
  end

  config.vm.define "WebServer2" do |app02|
    app02.vm.box = "ubuntu/bionic64"
    app02.vm.network "private_network", ip: "192.168.33.13"
    #app02.vm.network "forwarded_port", guest_ip: "10.0.2.18", guest: 8080, host_ip:"127.0.0.1", host: 8808
    app02.vm.hostname = "app02"
    app02.vm.synced_folder ".", "/vagrant", type: "nfs"
    app02.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--name", "app02"]
      vb.memory = "1024"
      vb.cpus = "1"
    end
    app02.vm.provision "shell", inline: <<-SHELL
    sudo sed -i 's/XKBLAYOUT="us"/XKBLAYOUT="ch"/g' /etc/default/locale
    sudo apt-get update -y
    sudo apt-get upgrade -y
    echo '127.0.0.1 localhost app02\n192.168.33.12 app01\n192.168.33.12 lb01\n192.168.33.10 acontrol' > /etc/hosts
    #cat /vagrant/id_rsa.pub >>~/.ssh/authorized_keys
SHELL
  end

end